### ISSUE TITLE
Redirect to HTTPS connections where appropriate

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#132]
Just a thought, maybe it'll be a terrible idea but just writing it down.

**Comment by czlee** [comment]
Actually, the SSL Endpoint $20/month thing is only for custom domains. Heroku sites come with SSL already enabled. So we just have to force it in Django for the admin interface and submission forms.

**Comment by czlee** [comment]
Jotting down some notes:
* I think Heroku's routing uses what Django would consider a proxy: https://devcenter.heroku.com/articles/http-routing#routing and https://devcenter.heroku.com/articles/http-routing#heroku-headers
* Local installations might not and we should probably configure settings.py not to use `SECURE_SSL_PROXY_HEADER`, but then, we advise against making local installations internet-accessible anyway, so it's not so big an issue.
* We could either set `SECURE_SSL_REDIRECT` and `SECURE_REDIRECT_EXEMPT`, or if we want the information to be in views, do something like this: https://gist.github.com/ckinsey/9709984
    * We probably want this to be tied to `@login_required`, so maybe replacing that decorator/mixin with one that includes both a login requirement and SSL would be easiest.
* Not sure if adding `SecurityMiddleware` explicitly is necessary.
* `SESSION_COOKIE_SECURE` and `CSRF_COOKIE_SECURE` might need to be set, because of user logins.

**Comment by czlee** [comment]
Adding to Bengal because it seems like the kind of thing a maturing project should do, but I'm not strictly set on doing it for Bengal if we don't think we can.

**Comment by philipbelesky** [comment]
Just glancing over this quickly, but if SSL isn't provided for custom domains, I assume that means that anyone installing tabbycat on a custom domain needs to purchase/obtain an SSL endpoint?

**Comment by czlee** [comment]
That would match my interpretation, but I'm not fully confident in my interpretation.

**Comment by philipbelesky** [comment]
That is pretty annoying, and would significantly increase the complexity and costs of running a large tournament, assuming it can't be made optional :/

**Comment by philipbelesky** [comment]
Ok, removing from Bengal unless info comes to light that means custom domains do not need paid SSL endpoints

**Comment by czlee** [comment]
I don't think the need for SSL endpoints is a dealbreaker. For large tournaments (like Australs) this should just be part of the cost of running the tournament, otherwise if it's only the admin interface we're trying to protect, tab room can just use the herokuapp.com address (while the public interface remains on http). In any case, we can make this feature optional.

Agree with not aiming for Bengal though.

**Comment by czlee** [comment]
Maybe we should just force all connections to be on HTTPS when on Heroku, including public pages? It looks like current recommendations are just to use HTTPS always, even if not handling sensitive information:
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Also, I guess public submission forms also should be submitted via SSL.

Though mainly this is probably just less hassle than trying to discriminate between admin views and public views—it's just the setting of a bunch of variables in the settings.py file.

**Comment by czlee** [comment]
Do we have a clean means of detecting if the site's on Heroku? I used the existence of `DJANGO_SECRET_KEY` as a proxy, but maybe we should implement something more proper? I can't see any easy options though, not without putting it into the app.json file in a way that users could mess up in the "Deploy" form.

**Comment by czlee** [comment]
Okay. I think what's currently in the `feature/#132-https` branch is functional, and the only thing holding it back is whatever elegance it lacks owing to our not grouping Heroku settings under a single `if` statement.

Because Heroku doesn't play nicely with the hash symbol in branches, I've also pushed it to an `https` branch, which can be deployed here: https://heroku.com/deploy?template=https://github.com/czlee/tabbycat/tree/https

Points to note:
- It **only** enables HTTPS redirects if it thinks it's on Heroku (by checking for `DJANGO_SECRET_KEY`).
- Enabling HTTPS redirects would break Travis CI, because some requests will return 301 (for the redirect) rather than 200 or 302 [(build #1697)](https://travis-ci.org/czlee/tabbycat/builds/203005426).
- You can disable HTTPS redirects by setting the environment variable `DISABLE_HTTPS_REDIRECTS` to `disable`. It will take effect immediately for all requests from new users. However, because cookies from any earlier visitors will have been marked secure (because I set the [`SESSION_COOKIE_SECURE`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-SESSION_COOKIE_SECURE) and [`CSRF_COOKIE_SECURE`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-CSRF_COOKIE_SECURE) settings), their browsers will still redirect to HTTPS until they figure out how to instruct their browser not to. (I thought clearing cookies would do the trick, but I've had some difficulty getting my browser to revert to HTTP, even in incognito, even though browsers that haven't already visited the site work fine with HTTP.)
- This will break custom domains. However, my pick is that anyone who went to the effort of setting up a custom domain will be competent enough to either install an SSL certificate for their custom domain, or disable HTTPS redirects as described above (if they don't want to pay for an SSL certificate), and that lay users will always make do with the *.herokuapp.com site, which works fine with HTTPS.

Since most of our users run on *.herokuapp.com, and since we should probably take internet security more seriously, my current inclination is that we should just enable HTTPS  redirects by default on all Heroku sites, and provide a means to disable it (`DISABLE_HTTPS_REDIRECTS`). That means need not be accessible to lay users, because you would only ever need to if you have a custom domain, which requires a (modest) technical background in the first place. Of course, we'd need a page in documentation to explain this.

In particular, the setting is _not_, and would not be, available through the Tabbycat UI.

The one group this adversely affects are lay users who want to run *.herokuapp.com on HTTP. With HTTPS having been widely supported for many years, I'm inclined say we should just tell them not to.

**Comment by philipbelesky** [comment]
Yea, I can't think of any general reason not to use HTTPS. Agree we should probably have a more consolidated `ON_HEROKU` variable (but be very sure that it is always set - perhaps it could be done in `post_deploy`). There might also be a way to specify a heroku-specific ENV file or something. 

It's regrettable custom domains are harder to setup, but fine I guess. Could we ensure `DISABLE_HTTPS_REDIRECTS` is set from an environment variable rather than from modifications in `settings.py` (so updates don't have to worry about overwriting settings)?

**Comment by czlee** [comment]
Oh, totally. Sorry, should have been clearer: in current implementation, `DISABLE_HTTPS_REDIRECTS` is an environment variable (and it's actually not a setting at all, it just switches an `if` statement that sets the relevant Django settings). See 00fad4ebaa0811d36c65e02434e061a27db81bf3.

`post_deploy` could work, though now that I think about it we should also try to make sure it works if instead of using the Deploy button, you launch a Heroku app from the command line (so it doesn't use app.json).

**Comment by philipbelesky** [comment]
Yea, I was thinking that even if we set it in the deploy button process and the deploy script process we are still missing a few edge cases like manual deployment, in which case setting it in `post_deploy` (if it isn't already set) is probably the easiest way to cover all options.

**Comment by czlee** [comment]
Sounds good to me =)
